#!/bin/sh

# Copy and amend the template from
# https://llvm.org/docs/GettingStarted.html#stand-alone-builds

build_llvm=/home/merle/projects/triton-outputs/build-llvm
build_triton=/home/merle/projects/triton-outputs/build-triton
installprefix=/home/merle/projects/triton-outputs/install
llvm=/home/merle/projects/llvm-project
triton=/home/merle/projects/triton
mkdir -p $build_llvm
mkdir -p $build_triton
mkdir -p $installprefix

cmake -G Ninja -S $llvm/llvm -B $build_llvm \
   -DLLVM_ENABLE_PROJECTS=mlir \
   -DLLVM_BUILD_EXAMPLES=ON \
   -DLLVM_TARGETS_TO_BUILD="X86;NVPTX;AMDGPU" \
   -DLLVM_ENABLE_ASSERTIONS=ON \
   -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_LLD=ON \
   -DCMAKE_BUILD_TYPE=Release \
   -DLLVM_CCACHE_BUILD=ON \
   -DLLVM_INSTALL_UTILS=ON \
   -DCMAKE_INSTALL_PREFIX=$installprefix

ninja -C $build_llvm install

cmake -G Ninja -S $triton -B $build_triton \
    -DMLIR_DIR=$installprefix/lib/cmake/mlir \
    -DLLVM_EXTERNAL_LIT=$build_llvm/bin/llvm-lit

ninja -C $build_triton

# ninja -C $build_triton check-triton-lit-tests

# ninja -C $build_triton mlir-doc
